name: keepalive-random

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: keepalive-random
  cancel-in-progress: true

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect target file
        id: detect
        run: |
          if [ -f "app.py" ]; then
            echo "target=app.py" >> $GITHUB_OUTPUT
          elif [ -f "streamlit_app.py" ]; then
            echo "target=streamlit_app.py" >> $GITHUB_OUTPUT
          else
            echo "::error::No se encuentra app.py ni streamlit_app.py en la raíz del repo."
            exit 1
          fi

      - name: Decide if commit is needed
        id: decide
        run: |
          STATE_FILE=".github/last_keepalive.txt"
          mkdir -p .github
          NOW=$(date +%s)

          if [ ! -f "$STATE_FILE" ]; then
            echo $NOW > $STATE_FILE
            echo "commit=yes" >> $GITHUB_OUTPUT
            exit 0
          fi

          LAST=$(cat $STATE_FILE)
          ELAPSED_SEC=$(( NOW - LAST ))
          ELAPSED_H=$(( ELAPSED_SEC / 3600 ))

          RANDOM_DELAY=$(( ( RANDOM % 3 ) + 10 ))

          echo "Han pasado ${ELAPSED_H}h; objetivo aleatorio: ${RANDOM_DELAY}h"

          if [ "$ELAPSED_H" -ge "$RANDOM_DELAY" ]; then
            echo $NOW > $STATE_FILE
            echo "commit=yes" >> $GITHUB_OUTPUT
          else
            echo "commit=no" >> $GITHUB_OUTPUT
          fi

      - name: Touch app file
        if: steps.decide.outputs.commit == 'yes'
        run: |
          printf "\n# keepalive %s\n" "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "${{ steps.detect.outputs.target }}"

      - name: Commit & push
        if: steps.decide.outputs.commit == 'yes'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ steps.detect.outputs.target }}" .github/last_keepalive.txt
          git commit -m "keepalive: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push
